files:
  - source: /docs/*.md
    translation: /docs/%two_letters_code%/%original_file_name%
  - source: /docs/academy/*.md
    translation: /docs/%two_letters_code%/academy/%original_file_name%
  - source: /docs/create/*.md
    translation: /docs/%two_letters_code%/create/%original_file_name%
  - source: /docs/faqs/*.md
    translation: /docs/%two_letters_code%/faqs/%original_file_name%
  - source: /docs/miscellaneous/*.md
    translation: /docs/%two_letters_code%/miscellaneous/%original_file_name%
  - source: /docs/quickstart/*.md
    translation: /docs/%two_letters_code%/quickstart/%original_file_name%
  - source: /docs/run_publish/*.md
    translation: /docs/%two_letters_code%/run_publish/%original_file_name%
  - source: /docs/subquery_network/*.md
    translation: /docs/%two_letters_code%/subquery_network/%original_file_name%
  - source: /docs/subquery_data_node/*.md
    translation: /docs/%two_letters_code%/subquery_data_node/%original_file_name%
